#!/usr/bin/env node
"use strict";
/**
 * bootstrap.js — interactive setup wizard.
 *
 * 1. Asks for owner name + (optional) Telegram chat-id + timezone.
 * 2. Initializes mnemo.db at MNEMO_DB (default ./mnemo.db) using schema.sql + identity_schema.sql.
 * 3. Writes .env.local with the answers.
 * 4. Optionally seeds basic correction-patterns + traits.
 * 5. Prints next steps.
 *
 * Designed to be re-runnable safely.
 */
const fs = require("fs");
const path = require("path");
const readline = require("readline");
const Database = require("better-sqlite3");

const ROOT = __dirname;
const DEFAULT_DB = process.env.MNEMO_DB || path.join(ROOT, "mnemo.db");
const ENV_FILE = path.join(ROOT, ".env.local");

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q, def = "") => new Promise(resolve => {
  const prompt = def ? `${q} [${def}]: ` : `${q}: `;
  rl.question(prompt, ans => resolve((ans || "").trim() || def));
});

async function main() {
  console.log("\nMnemo bootstrap — let's set up a persistent memory for your agent.\n");

  const ownerName = await ask("Your name (used as agent's owner identity)", "owner");
  const dbPath = await ask("SQLite path", DEFAULT_DB);
  const tz = await ask("Your timezone offset from UTC in hours (e.g. 1 for CET, 2 for CEST, -5 for EST, 0 for UTC)", "0");
  const wantTelegram = (await ask("Enable Telegram channel? (y/N)", "n")).toLowerCase().startsWith("y");

  let chatId = null, tgToken = null;
  if (wantTelegram) {
    tgToken = await ask("Telegram bot token (from @BotFather)", "");
    chatId = await ask("Your Telegram chat-id (so the agent only listens to you)", "");
  }

  const wantSeedPatterns = (await ask("Seed minimal correction-patterns (correction/praise/promise)? (Y/n)", "y")).toLowerCase().startsWith("y");

  // 1) Init schema
  const db = new Database(dbPath);
  db.pragma("journal_mode = WAL");
  for (const f of ["schema.sql", "identity_schema.sql"]) {
    const p = path.join(ROOT, f);
    if (fs.existsSync(p)) db.exec(fs.readFileSync(p, "utf8"));
  }

  // 2) Owner self-snapshot
  db.prepare(`
    INSERT OR IGNORE INTO core_value (name, statement, scope, rationale)
    VALUES (?,?,?,?)
  `).run("owner_identity", `Owner of this Mnemo instance is "${ownerName}".`, "all", "Set during bootstrap.");

  // 3) Optional seed: minimal correction patterns
  if (wantSeedPatterns) {
    db.exec(`
      CREATE TABLE IF NOT EXISTS correction_pattern (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        pattern TEXT NOT NULL UNIQUE,
        classifier TEXT NOT NULL,
        actor_scope TEXT,
        trait_to_adjust TEXT,
        delta REAL,
        hit_count INTEGER NOT NULL DEFAULT 0,
        last_hit_at TEXT
      )
    `);
    const ins = db.prepare(`INSERT OR IGNORE INTO correction_pattern (pattern, classifier, actor_scope, trait_to_adjust, delta) VALUES (?,?,?,?,?)`);
    ins.run("\\b(stop|halt|nicht so|don't|no)\\b", "correction", ownerName, null, null);
    ins.run("\\b(perfekt|geil|nice|exactly|love it)\\b", "praise", ownerName, null, null);
    ins.run("\\b(I'll|i will|gonna|werd ich|mach ich)\\b", "promise", null, null, null);
  }

  // 4) Write .env.local
  const lines = [
    `# Generated by mnemo bootstrap on ${new Date().toISOString()}`,
    `MNEMO_DB=${dbPath}`,
    `MNEMO_OWNER_NAME=${ownerName}`,
    `MNEMO_TZ_OFFSET_HOURS=${tz}`,
  ];
  if (chatId) lines.push(`MNEMO_OWNER_CHAT_ID=${chatId}`);
  if (tgToken) lines.push(`TELEGRAM_BOT_TOKEN=${tgToken}`);
  fs.writeFileSync(ENV_FILE, lines.join("\n") + "\n");

  db.close();
  rl.close();

  console.log(`\n  ✓ DB initialized at ${dbPath}`);
  console.log(`  ✓ Settings written to ${ENV_FILE}`);
  console.log(`\nNext steps:`);
  console.log(`  - Start the daemon:    node daemon.js   (or: npm start)`);
  console.log(`  - Compute embeddings:  node embedding_writer.js`);
  console.log(`  - Wire MCP:            claude mcp add mnemo --transport stdio -- node ${path.join(ROOT, "mcp.js")}`);
  console.log(`  - Browse exports:      node export_declarative.js && cat exports/SOUL.md`);
  console.log(``);
}

main().catch(e => { console.error(e); process.exit(1); });
