#!/usr/bin/env node
"use strict";
/**
 * Interactive setup wizard.
 *
 * The public repository ships no private identity, company, agent, server, or
 * pricing data. This wizard creates those files locally from neutral templates.
 */
const fs = require("fs");
const path = require("path");
const readline = require("readline");
const Database = require("better-sqlite3");

const ROOT = __dirname;
const REPO_ROOT = path.resolve(ROOT, "..", "..");
const DEFAULT_DB = process.env.MNEMO_DB || path.join(ROOT, "mnemo.db");
const ENV_FILE = path.join(ROOT, ".env.local");
const HOOK_ENV_FILE = path.join(REPO_ROOT, ".mnemo-hook.env");

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q, def = "") => new Promise(resolve => {
  const prompt = def ? `${q} [${def}]: ` : `${q}: `;
  rl.question(prompt, ans => resolve((ans || "").trim() || def));
});

function cleanScope(value) {
  return String(value || "personal")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "") || "personal";
}

function parseAgents(value) {
  return String(value || "")
    .split(",")
    .map(s => s.trim().toLowerCase())
    .filter(Boolean);
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function writeJson(file, data) {
  fs.writeFileSync(file, JSON.stringify(data, null, 2) + "\n");
}

function writeEnv(file, entries) {
  const lines = [`# Generated by mnemo bootstrap on ${new Date().toISOString()}`];
  for (const [key, value] of entries) {
    if (value === undefined || value === null || value === "") continue;
    lines.push(`${key}=${String(value)}`);
  }
  fs.writeFileSync(file, lines.join("\n") + "\n");
}

async function main() {
  console.log("\nMnemo bootstrap - set up persistent memory for your agent/team.\n");

  const ownerName = await ask("Your name (owner identity)", "owner");
  const scopeName = cleanScope(await ask("Private scope name (company, team, or personal handle)", "personal"));
  const mainAgent = cleanScope(await ask("Primary agent name", "agent"));
  const otherAgents = parseAgents(await ask("Other agents, comma-separated (optional)", ""));
  const mission = await ask("What should this agent/team help you do?", "remember context, coordinate work, and avoid forgotten tasks");
  const firstProject = await ask("First project/workspace name (optional)", "");
  const dbPath = await ask("SQLite path", DEFAULT_DB);
  const tz = await ask("Timezone offset from UTC in hours (example: 1, 2, -5, 0)", "0");
  const wantTelegram = (await ask("Enable Telegram channel? (y/N)", "n")).toLowerCase().startsWith("y");

  let chatId = null;
  let tgToken = null;
  if (wantTelegram) {
    tgToken = await ask("Telegram bot token", "");
    chatId = await ask("Owner Telegram chat-id", "");
  }

  const wantSeedPatterns = (await ask("Seed minimal correction/praise/promise patterns? (Y/n)", "y")).toLowerCase().startsWith("y");

  const db = new Database(dbPath);
  db.pragma("journal_mode = WAL");
  for (const f of ["schema.sql", "identity_schema.sql"]) {
    const p = path.join(ROOT, f);
    if (fs.existsSync(p)) db.exec(fs.readFileSync(p, "utf8"));
  }

  const coreValue = db.prepare(`
    INSERT OR IGNORE INTO core_value (name, statement, scope, rationale)
    VALUES (?,?,?,?)
  `);
  coreValue.run("owner_identity", `Owner of this Mnemo instance is "${ownerName}".`, "all", "Set during bootstrap.");
  coreValue.run("operating_scope", `Default Mnemo scope is "${scopeName}".`, "all", "Set during bootstrap.");
  coreValue.run("agent_roster", `Active agents: ${[mainAgent, ...otherAgents].join(", ") || mainAgent}.`, "all", "Set during bootstrap.");
  coreValue.run("mission", mission, "all", "Set during bootstrap.");
  coreValue.run(
    "identity_must_persist",
    "Agents must reload owner identity, their own role, core values, preferences, open promises, and project rules at the start of every meaningful session.",
    "all",
    "Prevents identity drift across sessions."
  );
  coreValue.run(
    "token_efficiency",
    "Agents must search small, inspect compact IDs/timelines first, and fetch full memories only for selected records.",
    "all",
    "Prevents wasting context window and tokens."
  );

  if (wantSeedPatterns) {
    db.exec(`
      CREATE TABLE IF NOT EXISTS correction_pattern (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        pattern TEXT NOT NULL UNIQUE,
        classifier TEXT NOT NULL,
        actor_scope TEXT,
        trait_to_adjust TEXT,
        delta REAL,
        hit_count INTEGER NOT NULL DEFAULT 0,
        last_hit_at TEXT
      )
    `);
    const ins = db.prepare("INSERT OR IGNORE INTO correction_pattern (pattern, classifier, actor_scope, trait_to_adjust, delta) VALUES (?,?,?,?,?)");
    ins.run("\\b(stop|halt|not like that|don't|no)\\b", "correction", ownerName, null, null);
    ins.run("\\b(perfect|nice|exactly|love it|good)\\b", "praise", ownerName, null, null);
    ins.run("\\b(I'll|i will|going to|will do)\\b", "promise", null, null, null);
  }

  const factsDir = path.join(ROOT, "facts");
  fs.mkdirSync(factsDir, { recursive: true });
  const factsPath = path.join(factsDir, `${scopeName}.json`);
  const rulesPath = path.join(factsDir, `${scopeName}-project-rules.json`);

  if (!fs.existsSync(factsPath)) {
    const facts = readJson(path.join(factsDir, "example.json"));
    facts._comment = "PRIVATE LOCAL FILE - edit for your own team/company. Do not commit real facts.";
    facts._meta.scope = scopeName;
    facts._meta.updated = new Date().toISOString().slice(0, 10);
    facts.owner = { name: ownerName };
    facts.agents = [mainAgent, ...otherAgents].map(name => ({ name, role: "agent", status: "active" }));
    facts.mission = { summary: mission };
    writeJson(factsPath, facts);
  }

  if (!fs.existsSync(rulesPath)) {
    const rules = readJson(path.join(factsDir, "example-project-rules.json"));
    rules._comment = "PRIVATE LOCAL FILE - edit project rules before enabling blocking hooks. Do not commit real project rules.";
    rules._meta.scope = scopeName;
    rules._meta.updated = new Date().toISOString().slice(0, 10);
    if (firstProject) rules.projects[0].name = firstProject;
    writeJson(rulesPath, rules);
  }

  const agents = [mainAgent, ...otherAgents].join(",");
  writeEnv(ENV_FILE, [
    ["MNEMO_DB", dbPath],
    ["MNEMO_OWNER_NAME", ownerName],
    ["MNEMO_DEFAULT_SCOPE", scopeName],
    ["MNEMO_SCOPE", scopeName],
    ["MNEMO_DEFAULT_AGENT", mainAgent],
    ["MNEMO_AGENT", mainAgent],
    ["MNEMO_LOCAL_AGENTS", agents],
    ["MNEMO_FACTS_DIR", factsDir],
    ["MNEMO_TZ_OFFSET_HOURS", tz],
    ["MNEMO_OWNER_CHAT_ID", chatId],
    ["TELEGRAM_BOT_TOKEN", tgToken]
  ]);

  writeEnv(HOOK_ENV_FILE, [
    ["MNEMO_OWNER_NAME", ownerName],
    ["MNEMO_DEFAULT_SCOPE", scopeName],
    ["MNEMO_SCOPE", scopeName],
    ["MNEMO_DEFAULT_AGENT", mainAgent],
    ["MNEMO_AGENT", mainAgent],
    ["MNEMO_FACTS_DIR", factsDir],
    ["MNEMO_PROJECT", firstProject]
  ]);

  db.close();
  rl.close();

  console.log(`\n  OK DB initialized at ${dbPath}`);
  console.log(`  OK Settings written to ${ENV_FILE}`);
  console.log(`  OK Private facts written to ${factsPath}`);
  console.log(`  OK Private project-rule seed written to ${rulesPath}`);
  console.log(`  OK Hook env written to ${HOOK_ENV_FILE}`);
  console.log("\nNext steps:");
  console.log("  - Start daemon:        npm run daemon");
  console.log(`  - Wire MCP server:     node ${path.join(ROOT, "mcp.js")}`);
  console.log("  - Read agent guide:    AGENTS.md");
  console.log("  - Enable hooks only after a smoke test with MNEMO_HOOK_BLOCK=0");
  console.log("");
}

main().catch(e => { console.error(e); process.exit(1); });
