#!/usr/bin/env node
"use strict";
/**
 * Non-interactive bootstrap for CI, containers, and scripted installs.
 */
const fs = require("fs");
const path = require("path");
const Database = require("better-sqlite3");

const ROOT = __dirname;
const REPO_ROOT = path.resolve(ROOT, "..", "..");
const dbPath = process.env.MNEMO_DB || path.join(ROOT, "mnemo.db");
const ENV_FILE = path.join(ROOT, ".env.local");
const HOOK_ENV_FILE = path.join(REPO_ROOT, ".mnemo-hook.env");

function cleanScope(value) {
  return String(value || "personal").trim().toLowerCase().replace(/[^a-z0-9_-]/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "") || "personal";
}

function writeEnv(file, entries) {
  const lines = [`# Generated by mnemo bootstrap_auto on ${new Date().toISOString()}`];
  for (const [key, value] of entries) {
    if (value === undefined || value === null || value === "") continue;
    lines.push(`${key}=${String(value)}`);
  }
  fs.writeFileSync(file, lines.join("\n") + "\n");
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function writeJson(file, data) {
  fs.writeFileSync(file, JSON.stringify(data, null, 2) + "\n");
}

const ownerName = process.env.MNEMO_OWNER_NAME || "owner";
const scopeName = cleanScope(process.env.MNEMO_DEFAULT_SCOPE || process.env.MNEMO_SCOPE || "personal");
const primaryAgent = cleanScope(process.env.MNEMO_AGENT || process.env.MNEMO_DEFAULT_AGENT || "agent");
const agents = String(process.env.MNEMO_LOCAL_AGENTS || primaryAgent).split(",").map(s => cleanScope(s)).filter(Boolean);
const tz = process.env.MNEMO_TZ_OFFSET_HOURS || "0";
const mission = process.env.MNEMO_MISSION || "remember context, coordinate work, and avoid forgotten tasks";
const firstProject = process.env.MNEMO_PROJECT || "";

console.log("\nMnemo auto-bootstrap starting...\n");

const db = new Database(dbPath);
db.pragma("journal_mode = WAL");

for (const f of ["schema.sql", "identity_schema.sql"]) {
  const p = path.join(ROOT, f);
  if (fs.existsSync(p)) {
    db.exec(fs.readFileSync(p, "utf8"));
    console.log(`  OK Applied ${f}`);
  }
}

const coreValue = db.prepare("INSERT OR IGNORE INTO core_value (name, statement, scope, rationale) VALUES (?,?,?,?)");
coreValue.run("owner_identity", `Owner of this Mnemo instance is "${ownerName}".`, "all", "Set during bootstrap.");
coreValue.run("operating_scope", `Default Mnemo scope is "${scopeName}".`, "all", "Set during bootstrap.");
coreValue.run("agent_roster", `Active agents: ${agents.join(", ") || primaryAgent}.`, "all", "Set during bootstrap.");
coreValue.run("mission", mission, "all", "Set during bootstrap.");
coreValue.run("identity_must_persist", "Agents must reload owner identity, their own role, core values, preferences, open promises, and project rules at the start of every meaningful session.", "all", "Prevents identity drift across sessions.");
coreValue.run("token_efficiency", "Agents must search small, inspect compact IDs/timelines first, and fetch full memories only for selected records.", "all", "Prevents wasting context window and tokens.");

db.exec(`
  CREATE TABLE IF NOT EXISTS correction_pattern (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pattern TEXT NOT NULL UNIQUE,
    classifier TEXT NOT NULL,
    actor_scope TEXT,
    trait_to_adjust TEXT,
    delta REAL,
    hit_count INTEGER NOT NULL DEFAULT 0,
    last_hit_at TEXT
  )
`);
const ins = db.prepare("INSERT OR IGNORE INTO correction_pattern (pattern, classifier, actor_scope, trait_to_adjust, delta) VALUES (?,?,?,?,?)");
ins.run("\\b(stop|halt|not like that|don't|no)\\b", "correction", ownerName, null, null);
ins.run("\\b(perfect|nice|exactly|love it|good)\\b", "praise", ownerName, null, null);
ins.run("\\b(I'll|i will|going to|will do)\\b", "promise", null, null, null);

const factsDir = process.env.MNEMO_FACTS_DIR || path.join(ROOT, "facts");
fs.mkdirSync(factsDir, { recursive: true });
const factsPath = path.join(factsDir, `${scopeName}.json`);
const rulesPath = path.join(factsDir, `${scopeName}-project-rules.json`);

if (!fs.existsSync(factsPath)) {
  const facts = readJson(path.join(ROOT, "facts", "example.json"));
  facts._comment = "PRIVATE LOCAL FILE - edit for your own team/company. Do not commit real facts.";
  facts._meta.scope = scopeName;
  facts._meta.updated = new Date().toISOString().slice(0, 10);
  facts.owner = { name: ownerName };
  facts.agents = agents.map(name => ({ name, role: "agent", status: "active" }));
  facts.mission = { summary: mission };
  writeJson(factsPath, facts);
}

if (!fs.existsSync(rulesPath)) {
  const rules = readJson(path.join(ROOT, "facts", "example-project-rules.json"));
  rules._comment = "PRIVATE LOCAL FILE - edit project rules before enabling blocking hooks. Do not commit real project rules.";
  rules._meta.scope = scopeName;
  rules._meta.updated = new Date().toISOString().slice(0, 10);
  if (firstProject) rules.projects[0].name = firstProject;
  writeJson(rulesPath, rules);
}

writeEnv(ENV_FILE, [
  ["MNEMO_DB", dbPath],
  ["MNEMO_OWNER_NAME", ownerName],
  ["MNEMO_DEFAULT_SCOPE", scopeName],
  ["MNEMO_SCOPE", scopeName],
  ["MNEMO_DEFAULT_AGENT", primaryAgent],
  ["MNEMO_AGENT", primaryAgent],
  ["MNEMO_LOCAL_AGENTS", agents.join(",")],
  ["MNEMO_FACTS_DIR", factsDir],
  ["MNEMO_TZ_OFFSET_HOURS", tz]
]);

writeEnv(HOOK_ENV_FILE, [
  ["MNEMO_OWNER_NAME", ownerName],
  ["MNEMO_DEFAULT_SCOPE", scopeName],
  ["MNEMO_SCOPE", scopeName],
  ["MNEMO_DEFAULT_AGENT", primaryAgent],
  ["MNEMO_AGENT", primaryAgent],
  ["MNEMO_FACTS_DIR", factsDir],
  ["MNEMO_PROJECT", firstProject]
]);

db.close();

console.log(`  OK DB initialized at ${dbPath}`);
console.log(`  OK Settings written to ${ENV_FILE}`);
console.log(`  OK Private facts written to ${factsPath}`);
console.log(`  OK Private project-rule seed written to ${rulesPath}`);
console.log(`  OK Hook env written to ${HOOK_ENV_FILE}`);
